import React, { createContext, useContext, useState, useEffect, useMemo } from 'react';

const ThemeLanguageContext = createContext();

const dictionary = {
  vi: {
    // Navigation & Common
    classes: 'Danh sách lớp học',
    allStudents: 'Học sinh (Tất cả các lớp)',
    timetable: 'Thời khóa biểu',
    inquiries: 'Câu hỏi từ học viên',
    guide: 'Hướng dẫn sử dụng',
    logout: 'Đăng xuất',
    settings: 'Cài đặt tài khoản',
    refresh: 'Làm mới',
    save: 'Lưu',
    saving: 'Đang lưu...',
    saved: 'Đã lưu',
    cancel: 'Hủy',
    cancelBtn: 'Hủy',
    cancelDiscardBtn: 'Hủy bỏ',
    close: 'Đóng',
    closeBtn: 'Đóng',
    studentCodeCol: 'Student Code',
    studentCode: 'Student Code',
    exportGradeMatrix: 'Xuất Bảng Điểm (Excel/CSV)',
    attendanceStatusCol: 'Trạng thái điểm danh',
    noteCol: 'Ghi chú',
    sessionLabel: 'Buổi học',
    confirm: 'Xác nhận',
    edit: 'Sửa',
    delete: 'Xóa',
    search: 'Tìm kiếm nhanh...',
    actions: 'Thao tác',
    status: 'Trạng thái',
    createdAt: 'Ngày tạo',
    dueDate: 'Hạn nộp',
    score: 'Điểm số',
    feedback: 'Nhận xét',
    download: 'Tải về',
    copy: 'Sao chép',
    code: 'MÃ',
    home: 'Trang chủ',
    managingClass: 'Đang quản lý lớp:',
    teacherRole: 'DÀNH CHO GIÁO VIÊN',
    studentRole: 'DÀNH CHO HỌC SINH',
    onlineRequests: 'bạn xin học online',
    classesCount: 'lớp',
    teacherSubtitle: 'Dành cho Giáo viên',
    studentSubtitle: 'Dành cho Học sinh',
    onlineRequestsTooltip: 'bạn xin học online',
    previousClass: 'Lớp trước',
    nextClass: 'Lớp tiếp theo',
    copyCodeSuccess: 'Đã sao chép mã lớp để gửi cho học sinh!',
    exportingReport: 'Đang kết xuất báo cáo tuần theo chuẩn Word (.docx)...',
    exportSuccess: 'Đã xuất và tải xuống báo cáo tuần thành công!',
    accountSettings: 'Cài đặt tài khoản',
    classCode: 'MÃ',
    allClassesTimetable: 'Thời Khóa Biểu Tất Cả Các Lớp',
    classTimetableTitle: 'Thời Khóa Biểu Lớp',
    loadingTimetableMsg: 'Đang tải thời khóa biểu...',
    lightMode: 'Sáng',
    darkMode: 'Tối',
    pts: 'đ',
    mins: 'phút',
    hours: 'giờ',
    all: 'Tất cả',
    optional: 'Tùy chọn',
    required: 'Bắt buộc',
    stt: 'STT',
    fullName: 'Họ và tên',
    email: 'Email',
    joinDate: 'Ngày tham gia',
    back: 'Quay lại',
    reset: 'Đặt lại',
    loadingData: 'Đang tải dữ liệu...',

    // 3 Core Hubs (3 Tab Cốt Lõi cho Giáo Viên)
    hubSchedule: 'Bảng tin & Lịch học',
    hubAssessment: 'Bài tập & Đánh giá',
    hubManagement: 'Quản trị lớp học',

    // Class Sub-Tabs
    tabAnnouncements: 'Bảng tin lớp',
    tabSessions: 'Buổi học & Kế hoạch',
    tabTimetable: 'Thời khóa biểu',
    tabAssignments: 'Giao bài & Chấm điểm',
    tabStudents: 'Học sinh trong lớp',
    tabAttendance: 'Điểm danh chuyên cần',
    tabGradeMatrix: 'Ma trận điểm số',
    tabAnalytics: 'Heatmap & Cảnh báo',
    tabMaterials: 'Tài liệu & Sách',
    tabTeachers: 'Đội ngũ giáo viên',

    // Weekly Report
    exportWeeklyReport: 'Xuất Báo Cáo Tuần (Word)',
    selectWeek: 'Chọn tuần',

    // Announcements
    createAnnouncement: 'Đăng thông báo mới',
    announcementTitle: 'Tiêu đề thông báo',
    announcementContent: 'Nội dung thông báo...',
    pinAnnouncement: 'Ghim thông báo lên đầu',
    pinned: 'ĐÃ GHIM',
    unpin: 'Bỏ ghim',
    pin: 'Ghim',
    noAnnouncements: 'Chưa có thông báo nào trong lớp.',
    editAnnouncement: 'Chỉnh sửa thông báo',
    postNow: 'Đăng ngay',
    announcementsSubtitle: 'Thông báo chính thức, thông tin kiểm tra và tin tức quan trọng từ giáo viên',
    announcementsEmptyStudent: 'Bạn chưa tham gia lớp học nào để xem bảng tin.',
    classLabel: 'Lớp:',

    // Assignments & Feedback & Mistake Notebook
    remindUnsubmitted: 'Nhắc học sinh chưa nộp bài',
    doNotRemind: 'Không nhắc bài này',
    exportZip: 'Tải toàn bộ bài làm (ZIP)',
    speedGraderPrev: '‹ Học sinh trước',
    speedGraderNext: 'Học sinh sau ›',
    feedbackThread: 'Trao đổi & Phản hồi bài làm',
    sendReply: 'Gửi phản hồi',
    enterReplyPlaceholder: 'Nhập nội dung trao đổi với giáo viên...',
    recordAudio: 'Thu âm',
    stopRecording: 'Dừng thu',
    saveToMistakeNotebook: 'Lưu vào sổ tay lỗi sai',
    savedToNotebook: 'Đã lưu vào sổ tay lỗi sai',
    mistakeNotebookTitle: 'Sổ tay ôn tập lỗi sai',
    mistakeNotebook: 'Sổ tay lỗi',
    joinClassByCode: '+ Vào Lớp Bằng Mã',
    saveGradeAndFeedback: 'Lưu Điểm & Nhận Xét',
    savingGrade: 'Đang lưu điểm...',
    gradeScorePlaceholder: 'Nhập điểm (0 - 10)',
    rubricQuickChips: 'Gợi ý nhận xét nhanh:',
    unsubmittedStudentsRemind: 'Nhắc nhở học sinh chưa nộp',
    exportZipSubmissions: 'Xuất toàn bộ bài nộp (.ZIP)',
    speedGraderTitle: 'SpeedGrader - Chấm bài nhanh',
    mistakeNotebookHeading: 'Sổ Tay Ôn Tập Lỗi Sai',
    mistakeNotebookSubtitle: 'Tổng hợp các câu sai, kiến thức ngữ pháp và phát âm cần cải thiện',
    searchMistakesPlaceholder: 'Tìm kiếm lỗi sai, ghi chú...',
    filterAllMistakes: 'Tất cả lỗi sai',
    noMistakesYet: 'Chưa có lỗi sai nào được lưu vào sổ tay.',
    addedAtLabel: 'Ngày lưu:',
    reviewMistakeBtn: 'Đã ôn tập',

    // Student Portal - Classes Tab
    studentPortalTitle: 'Cổng Học Viên',
    myAssignments: 'Bài tập của tôi',
    mySchedule: 'Lịch học của tôi',
    myClasses: 'Lớp học của tôi',
    enrolledClassesTitle: 'Lớp Học Đã Tham Gia',
    enrolledClassesSubtitle: 'Danh sách các lớp bạn đã ghi danh qua mã lớp',
    joinMoreClasses: '+ Tham Gia Thêm Lớp Mới',
    noEnrolledClassesYet: 'Bạn chưa tham gia lớp học nào',
    askTeacherForCode: 'Hãy hỏi giáo viên Mã Lớp (Class Code) và bấm nút bên dưới để tham gia.',
    enterClassCode: 'Nhập Mã Lớp Học',
    inProgress: 'Đang học',
    period: 'Thời gian:',
    codeLabel: 'Mã:',

    // Student Portal - Schedule Tab
    timetableTitle: 'Thời Khóa Biểu',
    timetableSubtitle: 'Xem lịch học tuần (07:00 - 22:00), nội dung bài học, dặn dò chuẩn bị, làm bài tập và báo vắng',
    weeklyTimetableToggle: 'Thời khóa biểu tuần (07:00 - 22:00)',
    sessionListToggle: 'Danh sách bài học & Chuẩn bị',
    noScheduleAvailable: 'Chưa có lịch học nào',
    askTeacherForSchedule: 'Bạn chưa tham gia lớp nào hoặc giáo viên chưa lên lịch học. Bấm nút bên dưới để nhập mã vào lớp.',
    upcomingSessions: 'Buổi học sắp tới',
    noUpcomingSessions: 'Không có buổi học sắp tới nào.',
    pastSessions: 'Buổi học đã học',
    noPastSessions: 'Chưa có buổi học nào đã qua.',
    news: 'Tin tức',
    reportedAbsence: 'Đã báo vắng',
    onlineRequest: 'Xin học online',
    attendedOnline: 'Đã học Online',
    completed: 'Đã học',
    startsAt: 'Bắt đầu:',
    durationMinutesLabel: 'Thời lượng:',
    reason: 'Lý do:',
    reviewSubmission: 'Xem lại bài đã nộp',
    viewHomework: 'Xem bài tập',
    continueDraft: 'Tiếp tục làm bài (Bản nháp)',
    doHomework: 'Làm bài tập',
    multipleAssignmentsNotice: 'bài tập (chọn bên dưới)',
    cancelRequest: 'Hủy yêu cầu',
    attended: 'Đã tham gia',
    wasAbsent: 'Đã vắng',
    requestAbsenceOrOnline: 'Xin nghỉ / Học Online',
    reportAbsenceBtn: 'Báo vắng',
    teacherAnnouncement: 'Thông báo từ giáo viên',
    sessionDetailsAndPrep: 'Nội dung chi tiết & Dặn dò chuẩn bị',
    part: 'Phần',
    timeAllocation: 'Thời gian:',
    classActivity: 'Hoạt động trên lớp:',
    studentPrepRequired: 'Học sinh cần chuẩn bị:',
    noSpecialPrep: '(Không có yêu cầu chuẩn bị đặc biệt)',
    viewPastedText: 'Xem văn bản bài học đã dán',
    downloadHandout: 'Tải tài liệu:',
    noDetailedPlanYet: 'Chưa có kế hoạch chi tiết cho buổi học này.',
    linkedAssignments: 'Bài tập liên kết với buổi học này',
    gradedBadge: 'Đã chấm:',
    submittedBadge: 'Đã nộp bài',
    draftBadge: 'Bản nháp',
    notSubmittedBadge: 'Chưa nộp',
    doThisAssignment: 'Làm bài tập này',
    attachmentsCount: 'Tệp đính kèm',

    // Student Portal - Submission Modal
    submitHomework: 'Nộp bài tập',
    resubmitHomework: 'Nộp lại bài',
    submittedReview: 'Xem lại bài đã nộp',
    draftRestored: 'Đã khôi phục bản nháp bài làm tự động.',
    draftSaved: 'Bản nháp được lưu tự động.',
    submissionModalTitle: 'Nộp Bài Tập',
    assignmentInstructions: 'Yêu cầu bài tập:',
    noDetailedInstructions: 'Không có mô tả chi tiết',
    teacherAttachments: 'Tệp đính kèm của giáo viên',
    assessmentResultTitle: 'Kết Quả Đánh Giá & Nhận Xét',
    submissionStatusTitle: 'Trạng Thái Bài Nộp Của Bạn',
    teacherGradedDetailedNotice: 'Giáo viên đã chấm điểm và nhận xét chi tiết',
    submittedAwaitingGradeNotice: 'Đã nộp bài, đang chờ giáo viên chấm điểm',
    scoreLabel: 'Điểm:',
    awaitingGrade: 'Chờ chấm điểm',
    yourSubmittedContent: 'Nội dung bạn đã nộp:',
    attachedFileLabel: 'Tệp đính kèm:',
    downloadOrOpenFile: 'Tải về / Mở tệp ↗',
    deleteSubmissionNotice: 'Bạn có thể xóa bài này để nộp lại bài khác nếu cần chỉnh sửa.',
    deleteSubmissionBtn: 'Xóa bài đã nộp',
    deletingSubmission: 'Đang xóa...',
    storageNotice30Days: 'Lưu ý lưu trữ: Bài làm đã nộp được lưu giữ trong 1 tháng (30 ngày) kể từ ngày nộp lên hệ thống.',
    resubmitOrUpdate: 'Nộp lại / Cập nhật bài làm:',
    selectSubmissionFormat: 'Chọn định dạng nộp bài:',
    modeText: 'Văn bản',
    modeDocx: 'Tệp Docx',
    modeAudio: 'File Audio',
    modeRecord: 'Thu âm ngay',
    modeImage: 'Ảnh / Chụp ảnh',
    enterSubmissionTextLabel: 'Nhập nội dung bài làm của bạn:',
    enterSubmissionTextPlaceholder: 'Nhập nội dung trả lời câu hỏi tại đây...',
    uploadDocxLabel: 'Tải tệp Word bài làm (.docx, .doc):',
    uploadingFile: 'Đang tải file lên...',
    attachedLabel: 'Đã đính kèm:',
    uploadAudioLabel: 'Tải tệp âm thanh (.mp3, .wav, .m4a):',
    uploadingAudio: 'Đang tải file âm thanh lên...',
    submitWithPhotosLabel: 'Nộp bài bằng Hình ảnh / Bản chụp bài làm:',
    uploadFromDevice: 'Tải ảnh từ máy (.jpg, .png)',
    takePhoto: 'Chụp ảnh nộp bài',
    captureThisPhoto: 'Bấm chụp ảnh này',
    stopCamera: 'Tắt camera',
    uploadingPhoto: 'Đang tải ảnh lên hệ thống...',
    saveDraftBtn: 'Lưu bản nháp (chưa nộp)',
    submittingHomework: 'Đang nộp bài...',
    confirmSubmitHomework: 'Xác Nhận Nộp Bài',
    lessonHandoutModalTitle: 'Nội Dung Văn Bản Bài Học',

    // Student Portal - Absence Modal
    registerOnlineTitle: 'Đăng ký tham gia học Online',
    confirmAbsenceTitle: 'Xác nhận báo vắng buổi học',
    selectParticipationMode: 'Chọn hình thức tham gia:',
    requestOnlineOption: 'Xin học Online',
    onlineOptionDesc: 'Học qua Meet/Zoom, giữ vững 100% chuyên cần',
    recommendedBadge: 'Khuyên dùng',
    fullAbsenceOption: 'Nghỉ hẳn buổi học',
    fullAbsenceDesc: 'Vắng mặt, trừ 1 lượt trong hạn mức tháng',
    absenceQuotaBadge: 'Hạn mức 2 buổi/tháng',
    timePolicyLabel: 'Quy định thời gian:',
    atLeast4HoursNotice: 'Trước giờ học ít nhất 4 tiếng',
    monthlyQuotaLabel: 'Hạn mức nghỉ phép tháng này:',
    usedQuotaNotice: 'Đã dùng',
    howToGetLinkTitle: 'Cách thức nhận link phòng học:',
    howToGetLinkDesc: 'Sau khi bạn gửi yêu cầu, Thầy/Cô sẽ nhận được thông báo và đăng link Google Meet/Zoom lên mục Thông báo của buổi học. Bạn chỉ cần chú ý ô "Tin tức" nhấp nháy trên lịch để bấm vào link vào học nhé!',
    mandatoryCommitmentsTitle: 'Cam kết bù bài bắt buộc',
    commitmentDoc: 'Tôi cam kết sẽ xem lại tài liệu được yêu cầu trong buổi học',
    commitmentHomework: 'Tôi cam kết nộp đầy đủ bài tập được giao đúng thời hạn',
    commitmentImpact: 'Tôi hiểu rằng việc vắng học có thể ảnh hưởng tới khả năng tiếng anh của bản thân',
    reasonLabel: 'Lý do',
    reasonOnlinePlaceholder: 'Nhập lý do xin học online...',
    reasonAbsencePlaceholder: 'Nhập lý do xin nghỉ học...',
    confirmOnlineBtn: 'Xác nhận xin học Online',
    confirmAbsenceBtn: 'Xác nhận báo vắng',

    // Student Portal - Mobile Nav
    mobileNavAnnouncements: 'Bảng tin',
    mobileNavSchedule: 'Lịch học',
    mobileNavClasses: 'Lớp học',
    mobileNavMistakes: 'Sổ tay lỗi',
    mobileNavSettings: 'Cài đặt',

    // TimetableGrid
    timetableGridTitle: 'Thời khóa biểu tuần',
    prevWeek: 'Tuần trước',
    currentWeek: 'Tuần này',
    nextWeek: 'Tuần sau',
    assignmentStatusLegend: 'Trạng thái bài tập:',
    notStarted: 'Chưa làm',
    inProgressLegend: 'Đang làm dở',
    completedOrGraded: 'Đã làm / Đã chấm',
    classLegend: 'Lớp:',
    sessionDrawerTitle: 'Chi tiết buổi học',
    homeworkThisSession: 'Bài tập về nhà buổi này',
    dayMon: 'Thứ 2',
    dayTue: 'Thứ 3',
    dayWed: 'Thứ 4',
    dayThu: 'Thứ 5',
    dayFri: 'Thứ 6',
    daySat: 'Thứ 7',
    daySun: 'Chủ nhật',
    dayShortMon: 'T2',
    dayShortTue: 'T3',
    dayShortWed: 'T4',
    dayShortThu: 'T5',
    dayShortFri: 'T6',
    dayShortSat: 'T7',
    dayShortSun: 'CN',

    // Class Management (ClassList & ClassDashboard)
    classManagementTitle: 'Quản Lý Lớp Học',
    classListSubtitle: 'Danh sách tất cả các lớp giảng dạy của bạn',
    activityLibrary: 'Thư Viện Hoạt Động',
    addNewClass: '+ Thêm Lớp Mới',
    classCodeCol: 'Mã Lớp (Vào Lớp)',
    classNameCol: 'Tên lớp',
    startDateCol: 'Ngày bắt đầu',
    endDateCol: 'Ngày kết thúc',
    actionsCol: 'Thao tác',
    coTeacherBadge: 'Đồng giảng dạy',
    copyClass: 'Copy',
    leaveClass: 'Rời lớp',
    noClassesYetClickNew: 'Chưa có dữ liệu lớp học nào. Hãy bấm "Thêm Lớp Mới" để bắt đầu.',
    createClassModalTitle: 'Tạo Lớp Học Mới',
    updateClassModalTitle: 'Cập Nhật Lớp Học',
    updateClass: 'Cập nhật Lớp học',
    className: 'Tên lớp học',
    startDate: 'Ngày bắt đầu',
    endDate: 'Ngày kết thúc',
    classNameLabel: 'Tên lớp học',
    startDateLabel: 'Ngày bắt đầu',
    endDateLabel: 'Ngày kết thúc',
    termLabel: 'Thời hạn:',
    sixMonthsSemester: '+6 tháng (Chuẩn học kỳ)',
    threeMonths: '+3 tháng',
    oneYear: '+1 năm',
    storagePolicyNotice: 'Chính sách lưu trữ: Dữ liệu giáo viên (lớp, lịch học, sách, buổi học, giáo án) được lưu trữ trong 6 tháng hoặc đến khi bị xóa. Bài nộp của học viên lưu giữ 1 tháng từ ngày nộp lên hệ thống.',
    saveChanges: 'Lưu thay đổi',
    createClassBtn: 'Tạo mới',
    duplicateClassTitle: 'Nhân Bản Lớp Học',
    newClassNameLabel: 'Tên lớp học mới',
    startCopyingBtn: 'Bắt đầu sao chép',
    confirmDeleteClassTitle: 'Xác Nhận Xóa Lớp Học',
    confirmLeaveClassTitle: 'Xác Nhận Rời Khỏi Lớp Học',
    confirmDeleteClassDesc: 'Bạn có chắc chắn muốn xóa lớp học này không?',
    confirmLeaveClassDesc: 'Bạn có chắc chắn muốn rời khỏi lớp học đồng giảng dạy này không?',

    // Session Management (SessionList)
    selectAll: 'Chọn tất cả',
    deselectAll: 'Bỏ chọn',
    selectedSessionsCount: 'Đã chọn',
    batchDelete: 'Xóa hàng loạt',
    batchDeleting: 'Đang xóa hàng loạt...',
    addSessionBtn: '+ Thêm Buổi Học',
    allSessionsFilter: 'Tất cả buổi học',
    upcomingOnlyFilter: 'Chỉ xem chưa kết thúc',
    sectionsCount: 'học phần',
    noSectionsYet: 'Chưa có học phần',
    sessionEnded: 'Đã hoàn thành',
    onlineStudentsBox: 'bạn xin học Online',
    sendRoomLinkBtn: 'Gửi link phòng học',
    urgentAnnouncementTitle: 'Thông báo đột xuất cho học sinh:',
    editAnnouncementBtn: 'Sửa thông báo',
    hidePlanBtn: 'Ẩn kế hoạch',
    viewPlanBtn: 'Xem kế hoạch',
    addSectionBtn: '+ Thêm học phần',
    attendanceBtn: 'Điểm danh',
    moreOptions: 'Tùy chọn khác',
    copyNextWeek: 'Copy sang tuần sau (+7 ngày)',
    customCopySession: 'Tùy chỉnh sao chép (Copy)',
    copyPlanToAnother: 'Sao chép kế hoạch sang buổi khác',
    editSessionBtn: 'Sửa buổi học',
    deleteSessionBtn: 'Xóa buổi học',
    sectionLabel: 'Học phần',
    activityLabel: 'Hoạt động:',
    prepLabel: 'Học sinh cần chuẩn bị:',
    bookLabel: 'Sách:',
    pageLabel: 'Trang',
    handoutLabel: 'Tài liệu bài học:',
    viewTextBtn: 'Xem văn bản',
    downloadFileBtn: 'Tải tệp:',
    copySectionBtn: 'Copy học phần',
    noSessionsYetTitle: 'Chưa có buổi học nào được tạo trong lớp này.',
    noSessionsYetSubtitle: 'Hãy bấm "+ Thêm Buổi Học" để bắt đầu lên lịch giảng dạy.',
    createSessionModalTitle: 'Thêm Buổi Học Mới (+ Kế Hoạch Giảng Dạy)',
    topicLabel: 'Chủ đề buổi học',
    startTimeLabel: 'Thời gian bắt đầu',
    durationLabel: 'Thời lượng (phút)',
    detailedPlanOptional: 'Kế hoạch chi tiết của buổi học (Tùy chọn)',
    teachingContentLabel: 'Nội dung giảng dạy',
    selectFromLibrary: 'Chọn từ Thư Viện',
    handoutTypeNone: 'Không có',
    handoutTypeText: 'Dán văn bản',
    handoutTypeFile: 'Đính kèm tệp',
    addNextSectionBtn: '+ Thêm học phần tiếp theo',
    createSessionSubmitBtn: 'Tạo Buổi Học',
    editSessionModalTitle: 'Chỉnh Sửa Buổi Học',
    copySessionModalTitle: 'Sao Chép Buổi Học',
    includePlanCheckbox: 'Sao chép cả Kế hoạch giảng dạy chi tiết',
    startSessionCopyBtn: 'Bắt đầu sao chép',
    updateSectionModalTitle: 'Cập Nhật Học Phần',
    addSectionModalTitle: 'Thêm Học Phần Mới Vào Buổi Học',
    saveSectionBtn: 'Lưu học phần',
    copyPlanModalTitle: 'Sao Chép Kế Hoạch Giảng Dạy',
    targetSessionPicker: 'Chọn buổi học đích để dán kế hoạch:',
    pastePlanBtn: 'Dán Kế Hoạch Sang Buổi Này',
    urgentAnnouncementModalTitle: 'Thông Báo Đột Xuất Cho Buổi Học',
    announcementNoticeStudent: 'Nội dung thông báo (Sẽ hiển thị nổi bật cho học sinh):',
    deleteAnnouncementBtn: 'Xóa thông báo',
    saveAnnouncementBtn: 'Lưu thông báo',

    // Attendance Management (AttendanceManager)
    attendanceManagementTitle: 'Quản Lý Điểm Danh',
    bySessionMode: 'Điểm danh theo buổi',
    matrixMode: 'Ma trận chuyên cần',
    selectSessionLabel: 'Chọn Buổi học:',
    allPresentBtn: 'Tất cả có mặt',
    saveAttendanceBtn: 'Lưu Điểm Danh',
    presentStat: 'Có mặt',
    onlineStat: 'Học Online',
    lateStat: 'Đi muộn',
    excusedStat: 'Nghỉ có phép',
    unexcusedStat: 'Nghỉ không phép',
    unrecordedStat: 'Chưa điểm danh',
    statusPresent: 'Có mặt',
    statusOnline: 'Học Online',
    statusLate: 'Đi muộn',
    statusExcused: 'Nghỉ có phép',
    statusAbsent: 'Vắng',
    statusUnrecorded: 'Chưa điểm danh',
    exportAttendanceExcel: 'Xuất Excel',

    // Assignment Grade Matrix
    gradeMatrixTitle: 'Ma Trận Điểm Số',
    exportGradeMatrixExcel: 'Xuất Bảng Điểm (Excel/CSV)',
    reloadMatrixBtn: 'Tải lại dữ liệu',
    classSizeKpi: 'Sĩ số lớp',
    studentsKpi: 'học sinh',
    totalAssignmentsKpi: 'Tổng số bài tập',
    assignmentsKpi: 'bài',
    completionRateKpi: 'Tỷ lệ hoàn thành bài',
    classAvgScoreKpi: 'Điểm trung bình lớp',
    noGradesYet: 'Chưa có điểm',
    searchStudentPlaceholder: 'Tìm theo tên học sinh, email...',
    filterAllStudents: 'Tất cả học sinh',
    filterIncompleteSubmissions: 'Chưa nộp đủ bài',
    filterLowScores: 'Cần chú ý: Điểm < 5.0',
    filterPerfectScores: 'Xuất sắc & Đầy đủ',
    sortNameAsc: 'Sắp xếp: Tên A → Z',
    sortScoreDesc: 'Điểm trung bình (Cao → Thấp)',
    sortScoreAsc: 'Điểm trung bình (Thấp → Cao)',
    sortCompletionDesc: 'Tỷ lệ hoàn thành (Cao → Thấp)',
    sttCol: 'STT',
    studentCol: 'Học sinh',
    submittedCol: 'Đã nộp',
    avgScoreCol: 'ĐTB',
    quickGradeTitle: 'Chấm Điểm & Nhận Xét Bài Nộp',
    quickScoreLabel: 'Điểm bài làm (thang 10):',
    quickFeedbackLabel: 'Nhận xét của giáo viên:',
    quickGradeSaveBtn: 'Lưu Điểm Nhanh',

    // Student List (StudentList & AllStudentsList)
    enrolledStudentsTitle: 'Học Sinh Trong Lớp',
    allStudentsTitle: 'Học Sinh (Tất Cả Các Lớp)',
    addNewStudentBtn: '+ Thêm Học Sinh Mới',
    copyInfoBtn: 'Copy TT',
    copyToClassBtn: 'Sao chép lớp',
    removeFromClassBtn: 'Xóa khỏi lớp',
    deleteStudentAccountBtn: 'Xóa tài khoản',
    noStudentsInClass: 'Lớp học chưa có học sinh nào. Hãy bấm "+ Thêm Học Sinh Mới" để ghi danh học sinh vào lớp.',
    addStudentModalTitle: 'Thêm Học Sinh Mới',
    fullNameLabel: 'Họ và tên',
    emailLabel: 'Email',
    selectClassOptional: 'Gán vào lớp học (Tùy chọn):',
    assignToClassModalTitle: 'Gán Học Sinh Vào Lớp Học',
    assignBtn: 'Gán vào lớp',

    // Account Settings (AccountSettingsModal)
    profileTab: 'Thông tin cá nhân',
    enrolledClassesTab: 'Lớp học đã tham gia',
    securityTab: 'Đổi mật khẩu',
    dangerZoneTab: 'Khu vực nguy hiểm',
    personalInfoTitle: 'Cập Nhật Thông Tin Cá Nhân',
    fullNameRequiredMsg: 'Họ và tên không được để trống.',
    updateProfileBtn: 'Lưu thông tin',
    updatingProfile: 'Đang lưu...',
    changePasswordTitle: 'Đổi Mật Khẩu Đăng Nhập',
    currentPasswordLabel: 'Mật khẩu hiện tại',
    newPasswordLabel: 'Mật khẩu mới (tối thiểu 6 ký tự)',
    confirmPasswordLabel: 'Xác nhận mật khẩu mới',
    updatePasswordBtn: 'Đổi Mật Khẩu',
    updatingPassword: 'Đang cập nhật...',
    enrolledClassesListTitle: 'Danh Sách Lớp Bạn Đang Học',
    noEnrolledClasses: 'Bạn chưa tham gia lớp học nào.',
    leaveClassBtn: 'Rời lớp',
    leavingClass: 'Đang rời lớp...',
    dangerZoneTitle: 'Xóa Vĩnh Viễn Tài Khoản',
    dangerZoneDesc: 'Khi xóa tài khoản, toàn bộ dữ liệu học tập, bài làm và lịch sử của bạn sẽ bị xóa vĩnh viễn và không thể khôi phục.',
    deleteAccountWarning: 'Vui lòng gõ "XOA TAI KHOAN" để xác nhận:',
    deleteAccountConfirmInputLabel: 'Nhập chữ xác nhận',
    deleteAccountBtn: 'Xác Nhận Xóa Vĩnh Viễn',
    deletingAccount: 'Đang xóa tài khoản...',

    // Student List & All Students List Extended
    studentListTitle: 'Danh Sách Học Sinh',
    studentListSubtitle: 'Quản lý học viên đăng ký tham gia lớp học này',
    studentsUnit: 'học viên',
    searchStudentPlaceholder: 'Tìm theo tên hoặc email...',
    copyInfoFullBtn: 'Copy Thông Tin',
    copyToOtherClassBtn: 'Sang lớp khác',
    removeStudentFromClassBtn: 'Xóa khỏi lớp',
    addStudentToClassModalTitle: 'Thêm học sinh vào lớp',
    studentFullNameLabel: 'Họ và tên học sinh',
    emailIdentityLabel: 'Email (Định danh)',
    studentEmailExistNote: 'Nếu email đã tồn tại trong hệ thống, học sinh sẽ tự động được ghi danh vào lớp này.',
    confirmAddBtn: 'Xác nhận thêm',
    updateStudentModalTitle: 'Cập nhật thông tin học sinh',
    saveChangesBtn: 'Lưu thay đổi',
    copyStudentToOtherClassTitle: 'Sao Chép Học Sinh Sang Lớp Khác',
    enrollStudentPrefix: 'Ghi danh học sinh',
    intoAnotherClass: 'vào một lớp học khác.',
    noOtherClasses: 'Không có lớp học nào khác trong hệ thống để sao chép đến.',
    selectTargetClassLabel: 'Chọn lớp học đích',
    confirmCopyClassBtn: 'Xác nhận sao chép',
    removeStudentConfirmTitle: 'Xóa học sinh khỏi lớp',
    removeStudentConfirmDesc: 'Bạn có chắc chắn muốn hủy ghi danh học sinh',
    fromThisClassDesc: 'khỏi lớp này?',
    confirmDeleteStudentBtn: 'Đồng ý xóa',
    noStudentFoundMatch: 'Không tìm thấy học sinh phù hợp với từ khóa.',
    emptyClassStudentPrompt: 'Lớp học hiện chưa có học sinh nào. Hãy bấm nút "Thêm học sinh".',
    allStudentsTitleFull: 'Danh Sách Học Sinh (Tất Cả Các Lớp)',
    allStudentsSubtitleDesc: 'Tổng hợp toàn bộ học viên trong hệ thống, các lớp đang theo học và quản lý ghi danh',
    totalStudentsKpi: 'Tổng số học viên',
    totalClassesKpi: 'Tổng số lớp học',
    totalEnrollmentsKpi: 'Lượt ghi danh',
    notInAnyClassKpi: 'Chưa vào lớp nào',
    allClassesFilterOption: '-- Tất cả các lớp học --',
    studentsNotInAnyClassOption: 'Học viên chưa vào lớp nào',
    classColLabel: 'Lớp',
    enrolledClassesCol: 'Các lớp đang theo học',
    notInAnyClassBadge: 'Chưa tham gia lớp nào',
    unnamedStudent: 'Chưa đặt tên',
    loadingAllStudents: 'Đang tải danh sách học sinh toàn trường...',
    noStudentsFoundTitle: 'Không tìm thấy học sinh nào',
    noStudentsFoundSubtitle: 'Thử thay đổi từ khóa tìm kiếm hoặc bộ lọc lớp học.',
    noStudentsInSystemSubtitle: 'Chưa có học sinh nào trong hệ thống.',
    createStudentModalDesc: 'Tạo tài khoản học sinh và gán trực tiếp vào lớp học (tùy chọn)',
    emailGmailLabel: 'Email Gmail tài khoản',
    assignToClassImmediately: 'Gán vào lớp học ngay:',
    notAssignedYetOption: '-- Chưa gán lớp (Thêm vào hệ thống trước) --',
    addingStudentProgress: 'Đang thêm...',
    assignStudentModalTitle: 'Gán Học Sinh Vào Lớp',
    studentLabelPrefix: 'Học sinh:',
    selectClassToAddLabel: 'Chọn lớp muốn thêm học sinh vào:',
    selectOneClassPrompt: '-- Chọn một lớp học --',
    assigningToClass: 'Đang ghi danh...',
    addToClassBtn: 'Thêm vào lớp',

    // Account Settings Modal Extended
    accountSettingsTitle: 'Cài Đặt Tài Khoản',
    personalInfoTab: 'Thông tin cá nhân',
    myClassesTab: 'Lớp học của tôi',
    changePasswordTab: 'Đổi mật khẩu',
    emailLoginLabel: 'Địa chỉ Email (Định danh đăng nhập):',
    emailFixedNote: 'Email được cố định để liên kết bài nộp và lớp học.',
    fullNameDisplayLabel: 'Họ và tên hiển thị:',
    fullNamePlaceholder: 'Nhập họ và tên đầy đủ của bạn...',
    systemRoleLabel: 'Vai trò hệ thống:',
    studentRoleBadge: 'Học Viên (STUDENT)',
    teacherRoleBadge: 'Giáo Viên (TEACHER)',
    saveProfileChangesBtn: 'Lưu Thay Đổi Thông Tin',
    myClassesDesc: 'Danh sách các lớp bạn đã tham gia. Bạn có thể tự rời khỏi lớp nếu không còn theo học.',
    noEnrolledClassesMsg: 'Bạn hiện chưa tham gia lớp học nào.',
    classCodePrefix: 'Mã lớp:',
    teacherPrefix: 'GV:',
    leaveClassButton: 'Rời lớp học',
    leavingClassProgress: 'Đang rời...',
    currentPasswordInputLabel: 'Mật khẩu hiện tại:',
    currentPasswordInputPlaceholder: 'Nhập mật khẩu hiện tại...',
    newPasswordInputLabel: 'Mật khẩu mới:',
    newPasswordInputPlaceholder: 'Ít nhất 6 ký tự...',
    confirmNewPasswordInputLabel: 'Xác nhận mật khẩu mới:',
    confirmNewPasswordInputPlaceholder: 'Nhập lại mật khẩu mới...',
    updatePasswordSubmitBtn: 'Cập Nhật Mật Khẩu',
    updatingPasswordProgress: 'Đang đổi mật khẩu...',
    dangerZoneDeleteTitle: 'Xóa Vĩnh Viễn Tài Khoản',
    dangerZoneDeleteDesc: 'Hành động này sẽ xóa vĩnh viễn tài khoản của bạn cùng mọi dữ liệu liên kết (bài nộp, lớp học, ghi danh). Thao tác này không thể khôi phục.',
    dangerConfirmTextLabel: 'Nhập chữ XÓA TÀI KHOẢN để xác nhận:',
    dangerConfirmPlaceholder: 'XÓA TÀI KHOẢN',
    dangerDeleteAccountBtn: 'Tôi Hiểu Hậu Quả, Xóa Tài Khoản Vĩnh Viễn',
    deletingAccountProgress: 'Đang xóa...',
    logoutAccountBtn: 'Đăng xuất tài khoản',

    // SessionList & Teaching Plans Extended
    sessionsAndPlansTitle: 'Buổi Học & Kế Hoạch Giảng Dạy',
    sessionsUnit: 'buổi học',
    addNewSessionBtn: '+ Thêm Buổi Học Mới',
    sessionsSelected: 'Buổi học đang được chọn',
    copyToNextWeekBtn: 'Sao chép sang tuần sau (+7 ngày)',
    deleteSelectedSessionsBtn: 'Xóa các buổi đã chọn',
    deselectBtn: 'Bỏ chọn',
    noSessionsInClass: 'Chưa có buổi học nào trong lớp',
    createFirstSessionDesc: 'Bấm nút bên dưới để tạo buổi học đầu tiên kèm kế hoạch giảng dạy chi tiết cho học sinh.',
    addSessionAndPlanNow: '+ Thêm Buổi Học & Kế Hoạch Ngay',
    upcomingSessionsTitle: 'Buổi Học Sắp Tới',
    pastSessionsTitle: 'Buổi Học Đã Diễn Ra',
    sectionsCount: 'học phần',
    noSectionsYet: 'Chưa có học phần',
    sessionCompleted: 'Đã hoàn thành',
    startTimeLabel: 'Bắt đầu:',
    durationLabel: 'Thời lượng:',
    expectedEndTimeLabel: 'Dự kiến kết thúc:',
    studentsRequestedOnline: 'bạn xin học Online',
    sendRoomLinkBtn: 'Gửi link phòng học',
    urgentAnnouncementLabel: 'Thông báo đột xuất cho học sinh:',
    editAnnouncementBtn: 'Sửa thông báo',
    viewPlanBtn: 'Xem kế hoạch',
    hidePlanBtn: 'Ẩn kế hoạch',
    addSectionBtn: '+ Thêm học phần',
    attendanceBtn: 'Điểm danh',
    announcementBtn: 'Thông báo',
    copyToNextWeek7d: 'Copy sang tuần sau (+7 ngày)',
    customCopySession: 'Tùy chỉnh sao chép (Copy)',
    editUrgentNotice: 'Sửa thông báo đột xuất',
    addUrgentNotice: 'Thêm thông báo đột xuất',
    editSessionInfo: 'Chỉnh sửa thông tin',
    deleteThisSession: 'Xóa buổi học này',
    detailedPlanTitle: 'Kế Hoạch Giảng Dạy Chi Tiết',
    detailedPlanSubtitle: 'Học sinh sẽ xem được nội dung sách, dặn dò chuẩn bị và tài liệu này trong thời khóa biểu',
    copyPlanToAnotherSession: 'Sao chép kế hoạch sang buổi khác',
    addNewSectionPlanBtn: '+ Thêm Học Phần Mới',
    noSectionsInPlanMsg: 'Buổi học này chưa có học phần chi tiết nào.',
    inputFirstSectionBtn: '+ Nhập Học Phần Đầu Tiên',
    sectionPrefix: 'Học phần',
    timeAllocationLabel: 'Phân bổ thời gian:',
    lessonContentLabel: 'Nội dung bài học:',
    preparationLabel: 'Dặn dò chuẩn bị:',
    activityLabel: 'Hoạt động lớp:',
    handoutLabel: 'Tài liệu phát:',
    bookPageLabel: 'Trang sách:',
    downloadHandoutBtn: 'Tải tài liệu',
    viewHandoutTextBtn: 'Xem văn bản dặn dò',
    openBookPageBtn: 'Mở trang sách',
    editSectionBtn: 'Sửa',
    deleteSectionBtn: 'Xóa',
    activityLibraryBtn: 'Thư Viện Hoạt Động',
    processingStatus: 'Đang xử lý...',
    deletingStatus: 'Đang xóa...',
    deselectGroup: 'Bỏ chọn nhóm này',
    selectAllGroup: 'Chọn tất cả nhóm này',
    noUpcomingSessionsInClass: 'Không có buổi học sắp tới nào.',
    copySessionModalTitle: 'Tùy Chỉnh Sao Chép Buổi Học',
    copySessionModalSubtitle: 'Nhân bản buổi học này và tùy chỉnh lại thời gian hoặc tên theo ý bạn.',
    newSessionTopicLabel: 'Chủ đề buổi học mới',
    copyAllPlansCheckbox: 'Sao chép toàn bộ Kế hoạch & Học phần sang buổi mới',
    confirmDuplicateBtn: 'Xác nhận nhân bản',
    deleteSessionModalTitle: 'Xác Nhận Xóa Buổi Học',
    confirmDeleteSessionMsg: 'Bạn có chắc muốn xóa buổi học',
    confirmDeleteSessionWarning: 'Kế hoạch giảng dạy và dữ liệu điểm danh của buổi học này cũng sẽ bị xóa.',
    permanentDeleteBtn: 'Xóa vĩnh viễn',
    createSessionModalTitle: 'Thêm Buổi Học Mới',
    createSessionModalSubtitle: 'Lên lịch học và nhập trước kế hoạch giảng dạy chi tiết',
    step1SessionInfo: '1. Thông tin buổi học',
    step2TeachingPlan: '2. Nhập Kế hoạch giảng dạy chi tiết luôn cho buổi này',
    sessionTopicLabel: 'Chủ đề / Tên buổi học',
    enterTopicPlaceholder: 'Nhập chủ đề buổi học...',
    minutesUnit: 'Phút',
    createSessionAndPlanBtn: 'Tạo Buổi Học & Kế Hoạch',
    creatingStatus: 'Đang tạo...',
    editSessionModalTitle: 'Chỉnh Sửa Thông Tin Buổi Học',
    urgentAnnouncementModalTitle: 'Thông báo đột xuất cho buổi học',
    urgentAnnouncementInputLabel: 'Nội dung thông báo cho học sinh:',
    enterAnnouncementPlaceholder: 'Nhập thông báo...',
    deleteAnnouncementBtn: 'Xóa thông báo',
    saveAnnouncementBtn: 'Lưu thông báo',
    savingStatus: 'Đang lưu...',
    copyPlanModalTitle: 'Sao Chép Kế Hoạch Sang Buổi Học Khác',
    copyPlanModalSubtitle: 'Chọn buổi học đích trong lớp này để dán toàn bộ các học phần của kế hoạch hiện tại.',
    targetSessionLabel: 'Buổi học đích:',
    selectSessionPrompt: '-- Chọn buổi học --',
    pastePlanBtn: 'Dán kế hoạch',
    viewPastedTextTitle: 'Nội Dung Văn Bản Đã Dán',
    sectionModalAddTitle: 'Thêm Học Phần Vào Buổi Học',
    sectionModalEditTitle: 'Chỉnh Sửa Học Phần',
    saveSectionBtn: 'Lưu học phần',
    textbookAndPageLabel: 'Sách giáo khoa & Số trang (Tùy chọn)',
    openBookPickPageBtn: 'Mở sách & Chọn trang',
    selectTextbookPrompt: '-- Chọn sách giáo khoa của lớp --',
    pagePlaceholder: 'Trang (VD: 45)',
    sectionContentLabel: 'Nội dung học phần (Tên bài học / kiến thức)',
    enterSectionContentPlaceholder: 'Nhập nội dung học phần...',
    timeAllocationPrompt: 'Thời lượng (VD: 15 phút)',
    classActivityLabel: 'Hoạt động lớp học',
    pickFromActivityBankBtn: 'Chọn từ kho',
    unselectBtn: 'Bỏ chọn',
    studentHomePrepLabel: 'Dặn dò học sinh chuẩn bị bài ở nhà:',
    homePrepPlaceholder: 'Học sinh đọc trước trang 24, làm bài tập khởi động...',
    attachedHandoutLabel: 'Tài liệu đính kèm (Handout)',
    noHandoutOption: 'Không đính kèm Handout',
    pasteTextOption: 'Dán văn bản bài học',
    uploadFileOption: 'Tải tệp đính kèm (.pdf, .docx, .png...)',
    pasteTextareaPlaceholder: 'Dán toàn bộ văn bản hoặc bài đọc vào đây...',
    uploadingHandoutStatus: 'Đang tải file lên...',
    attachedPrefix: 'Đã đính kèm:',

    // Assignment Manager Extended
    assignmentManagementTitle: 'Quản Lý Giao Bài Tập',
    assignmentsUnit: 'bài tập',
    allSessionsOption: 'Tất cả buổi học',
    newAssignmentBtn: 'Giao Bài Mới',
    scheduledPublishPrefix: 'Chờ phát hành:',
    sessionTimePrefix: 'Thời gian học:',
    publishNowBtn: 'Phát hành ngay',
    duplicateBtn: 'Nhân bản',
    viewSubmissionsBtn: 'Xem bài nộp',
    hideSubmissionsBtn: 'Ẩn bài nộp',
    studentSubmissionsHeading: 'Danh sách bài làm của học sinh',
    allStatusFilter: 'Tất cả trạng thái',
    statusSubmitted: 'Đã nộp bài',
    statusGraded: 'Đã chấm điểm',
    statusUnsubmitted: 'Chưa nộp bài',
    submissionTimeCol: 'Thời gian nộp',
    unsubmittedStatus: 'Chưa nộp',
    lateSubmission: 'Nộp muộn',
    onTimeSubmission: 'Đúng hạn',
    gradeSubmissionBtn: 'Chấm bài',
    editGradeBtn: 'Sửa điểm',
    speedGraderAction: 'SpeedGrader',
    createAssignmentModalTitle: 'Giao Bài Tập Mới',
    editAssignmentModalTitle: 'Cập Nhật Bài Tập',
    associatedSessionLabel: 'Thuộc buổi học',
    assignmentTitleLabel: 'Tiêu đề bài tập',
    assignmentDescLabel: 'Nội dung / Yêu cầu bài tập',
    dueDateLabel: 'Hạn nộp bài',
    scheduledPublishLabel: 'Lên lịch phát hành tự động (Tùy chọn)',
    allowedSubmissionTypesLabel: 'Các hình thức nộp bài cho phép',
    allowTextType: 'Văn bản trực tiếp',
    allowDocxType: 'File văn bản Word / PDF',
    allowAudioType: 'Tải lên file ghi âm',
    allowRecordingType: 'Thu âm trực tiếp trên web',
    allowImageType: 'Chụp / Tải ảnh bài làm',
    attachmentsLabel: 'Tài liệu giáo viên đính kèm',
    uploadAttachmentBtn: '+ Thêm file đính kèm',
    viewSubmissionsList: 'Xem danh sách nộp',
    viewingSubmissions: 'Đang xem bài nộp',
    remindUnsubmitted: 'Nhắc chưa nộp',
    noReminderForThis: 'Không nhắc bài này',
    remindersDisabled: 'Đã tắt nhắc nhở',
    downloadZip: 'Tải file ZIP',
    totalStudentsLabel: 'Tổng số học viên:',
    submittedCountLabel: 'Đã nộp:',
    unsubmittedCountLabel: 'Chưa nộp:',
    loadingSubmissionsList: 'Đang tải danh sách bài nộp của học sinh...',
    studentCol: 'Học viên',
    statusCol: 'Trạng thái',
    submissionFormatCol: 'Hình thức nộp',
    scoreCol: 'Điểm số',
    actionCol: 'Thao tác',
    ungraded: 'Chưa chấm',
    viewAndGradeBtn: 'Xem bài & Chấm điểm',
    noSubmissionText: 'Không có bài',
    noAssignmentsYet: 'Chưa có bài tập nào',
    createFirstAssignmentPrompt: 'Bấm nút "Giao Bài Mới" để tạo bài tập cho học viên trong lớp',
    createFirstAssignmentBtn: 'Giao Bài Đầu Tiên',
    gradeAndFeedbackModalTitle: 'Chấm Điểm & Phản Hồi Bài Nộp',
    studentLabel: 'Học viên:',
    prevStudent: '‹ Trước',
    nextStudent: 'Tiếp ›',
    submissionContentTitle: 'Nội dung bài nộp của học viên',
    submittedAtLabel: 'Nộp lúc:',
    emptySubmissionNotice: '(Bài làm trống)',
    downloadDocxBtn: 'Tải tệp về xem',
    openOriginalImage: 'Mở ảnh gốc ↗',
    audioNotFound: 'Không tìm thấy đường dẫn tệp âm thanh.',
    imageNotFound: 'Không tìm thấy đường dẫn ảnh.',
    scoreInputLabel: 'Điểm số',
    scoreInputPlaceholder: 'VD: 8.5/10, Band 7.0, A+...',
    teacherFeedbackLabel: 'Nhận xét & Lời khuyên của Giáo viên (Feedback)',
    clickChipToInsert: 'Nhấp chip để chèn nhanh',
    feedbackPlaceholder: 'Nhận xét ưu điểm, điểm cần cải thiện, lỗi phát âm/ngữ pháp...',
    saveGradeAndFeedbackBtn: 'Lưu Điểm & Gửi Nhận Xét',
    savingGradeStatus: 'Đang lưu...',
    publishTimingLabel: 'Thời điểm mở bài tập cho học sinh',
    publishImmediately: 'Phát hành ngay',
    schedulePublishBtn: 'Hẹn giờ phát hành',
    scheduledPushTime: 'Thời gian mở bài tự động (Push)',
    max5Attachments: 'Đính kèm tệp đề bài (Tối đa 5 tệp)',
    selectedCount: 'Đã chọn:',
    uploadingAttachmentStatus: 'Đang tải tệp lên...',
    saveUpdateBtn: 'Lưu cập nhật',
    assignHomeworkBtn: 'Giao bài tập',
    unlimitedDue: 'Không giới hạn',
    loadingAssignmentsList: 'Đang tải danh sách bài tập...',
    dueDatePrefix: 'Hạn nộp:',
    allowedSubmissionTypes: 'Hình thức nộp cho phép:',
    attachedTaskFiles: 'Tệp đề bài đính kèm',

    // Login & Register Extended
    trainingSystemSubtitle: 'Hệ Thống Quản Lý Đào Tạo & Lớp Học',
    loginTab: 'Đăng Nhập',
    registerTab: 'Đăng Ký Tài Khoản Mới',
    emailLoginInput: 'Email đăng nhập',
    passwordInput: 'Mật khẩu',
    showPassword: 'Hiện mật khẩu',
    hidePassword: 'Ẩn mật khẩu',
    loginSubmitBtn: 'Đăng Nhập',
    authenticatingProgress: 'Đang xác thực...',
    registerFullNameLabel: 'Họ và tên',
    registerEmailLabel: 'Email Gmail',
    accountRoleLabel: 'Vai trò tài khoản',
    teacherRoleOption: 'Giáo Viên',
    studentRoleOption: 'Học Viên',
    passwordMinChars: 'Mật khẩu (ít nhất 6 ký tự)',
    confirmPasswordInput: 'Nhập lại mật khẩu',
    passwordMatch: 'Mật khẩu hoàn toàn trùng khớp',
    passwordMismatch: 'Mật khẩu chưa trùng khớp',
    registerSubmitBtn: 'Tạo Tài Khoản & Bắt Đầu',
    creatingAccountProgress: 'Đang tạo tài khoản...',
    orContinueWith: 'Hoặc tiếp tục với'
  },
  en: {
    // Navigation & Common
    classes: 'Class List',
    allStudents: 'All Students',
    timetable: 'Timetable',
    inquiries: 'Student Inquiries',
    guide: 'User Guide',
    logout: 'Log Out',
    settings: 'Account Settings',
    refresh: 'Refresh',
    save: 'Save',
    saving: 'Saving...',
    saved: 'Saved',
    cancel: 'Cancel',
    cancelBtn: 'Cancel',
    cancelDiscardBtn: 'Cancel',
    close: 'Close',
    closeBtn: 'Close',
    studentCodeCol: 'Student Code',
    studentCode: 'Student Code',
    exportGradeMatrix: 'Export Grade Matrix (CSV)',
    attendanceStatusCol: 'Attendance Status',
    noteCol: 'Note',
    sessionLabel: 'Session',
    confirm: 'Confirm',
    edit: 'Edit',
    delete: 'Delete',
    search: 'Quick search...',
    actions: 'Actions',
    status: 'Status',
    createdAt: 'Created At',
    dueDate: 'Due Date',
    score: 'Score',
    feedback: 'Feedback',
    download: 'Download',
    copy: 'Copy',
    code: 'CODE',
    home: 'Home',
    managingClass: 'Managing Class:',
    teacherRole: 'TEACHER PORTAL',
    studentRole: 'STUDENT PORTAL',
    onlineRequests: 'online requests',
    classesCount: 'classes',
    teacherSubtitle: 'Teacher Portal',
    studentSubtitle: 'Student Portal',
    onlineRequestsTooltip: 'students requested online',
    previousClass: 'Previous class',
    nextClass: 'Next class',
    copyCodeSuccess: 'Class code copied to clipboard!',
    exportingReport: 'Exporting weekly report in Word format (.docx)...',
    exportSuccess: 'Weekly report exported successfully!',
    accountSettings: 'Account Settings',
    classCode: 'CODE',
    allClassesTimetable: 'Timetable - All Classes',
    classTimetableTitle: 'Timetable for',
    loadingTimetableMsg: 'Loading timetable...',
    lightMode: 'Light',
    darkMode: 'Dark',
    pts: 'pts',
    mins: 'mins',
    hours: 'hours',
    all: 'All',
    optional: 'Optional',
    required: 'Required',
    stt: '#',
    fullName: 'Full Name',
    email: 'Email',
    joinDate: 'Joined Date',
    back: 'Back',
    reset: 'Reset',
    loadingData: 'Loading data...',

    // 3 Core Hubs
    hubSchedule: 'Announcements & Schedule',
    hubAssessment: 'Assignments & Assessment',
    hubManagement: 'Class Management',

    // Class Sub-Tabs
    tabAnnouncements: 'Class Announcements',
    tabSessions: 'Sessions & Plans',
    tabTimetable: 'Timetable',
    tabAssignments: 'Assignments & Grading',
    tabStudents: 'Enrolled Students',
    tabAttendance: 'Attendance Tracker',
    tabGradeMatrix: 'Grade Matrix',
    tabAnalytics: 'Heatmap & Alerts',
    tabMaterials: 'Materials & Books',
    tabTeachers: 'Teaching Staff',

    // Weekly Report
    exportWeeklyReport: 'Export Weekly Report (.docx)',
    selectWeek: 'Select week',

    // Announcements
    createAnnouncement: 'New Announcement',
    announcementTitle: 'Announcement Title',
    announcementContent: 'Enter announcement content...',
    pinAnnouncement: 'Pin announcement to top',
    pinned: 'PINNED',
    unpin: 'Unpin',
    pin: 'Pin',
    noAnnouncements: 'No announcements posted in this class yet.',
    editAnnouncement: 'Edit Announcement',
    postNow: 'Post Now',
    announcementsSubtitle: 'Official announcements, test updates, and important notices from teacher',
    announcementsEmptyStudent: 'You have not enrolled in any classes to view announcements.',
    classLabel: 'Class:',

    // Assignments & Feedback & Mistake Notebook
    remindUnsubmitted: 'Remind Pending Students',
    doNotRemind: 'Do Not Remind',
    exportZip: 'Export All Submissions (ZIP)',
    speedGraderPrev: '‹ Previous Student',
    speedGraderNext: 'Next Student ›',
    feedbackThread: 'Submission Discussion & Feedback',
    sendReply: 'Send Reply',
    enterReplyPlaceholder: 'Type a message to teacher...',
    recordAudio: 'Record Voice',
    stopRecording: 'Stop',
    saveToMistakeNotebook: 'Save to Mistake Notebook',
    savedToNotebook: 'Saved to Mistake Notebook',
    mistakeNotebookTitle: 'Personal Mistake Notebook',
    mistakeNotebook: 'Mistake Notebook',
    joinClassByCode: '+ Join with Code',
    saveGradeAndFeedback: 'Save Grade & Feedback',
    savingGrade: 'Saving grade...',
    gradeScorePlaceholder: 'Enter score (0 - 10)',
    rubricQuickChips: 'Quick feedback suggestions:',
    unsubmittedStudentsRemind: 'Remind pending students',
    exportZipSubmissions: 'Export all submissions (.ZIP)',
    speedGraderTitle: 'SpeedGrader - Fast Grading Workbench',
    mistakeNotebookHeading: 'Personal Mistake Notebook',
    mistakeNotebookSubtitle: 'Review mistakes, grammar issues, and pronunciation feedback',
    searchMistakesPlaceholder: 'Search mistakes, notes...',
    filterAllMistakes: 'All Mistakes',
    noMistakesYet: 'No mistakes saved in your notebook yet.',
    addedAtLabel: 'Saved date:',
    reviewMistakeBtn: 'Reviewed',

    // Student Portal - Classes Tab
    studentPortalTitle: 'Student Portal',
    myAssignments: 'My Assignments',
    mySchedule: 'My Schedule',
    myClasses: 'My Classes',
    enrolledClassesTitle: 'Enrolled Classes',
    enrolledClassesSubtitle: 'List of classes you enrolled in via class code',
    joinMoreClasses: '+ Join Another Class',
    noEnrolledClassesYet: 'You haven\'t joined any classes yet',
    askTeacherForCode: 'Ask your teacher for the Class Code and click below to join.',
    enterClassCode: 'Enter Class Code',
    inProgress: 'In Progress',
    period: 'Period:',
    codeLabel: 'Code:',

    // Student Portal - Schedule Tab
    timetableTitle: 'Timetable',
    timetableSubtitle: 'View weekly schedule (07:00 - 22:00), lesson plans, preparations, homework, and request absence',
    weeklyTimetableToggle: 'Weekly Timetable (07:00 - 22:00)',
    sessionListToggle: 'Session List & Prep',
    noScheduleAvailable: 'No Schedule Available',
    askTeacherForSchedule: 'You haven\'t joined any class or the teacher hasn\'t scheduled sessions yet. Click below to enter a class code.',
    upcomingSessions: 'Upcoming Sessions',
    noUpcomingSessions: 'No upcoming sessions scheduled.',
    pastSessions: 'Past Sessions',
    noPastSessions: 'No past sessions recorded.',
    news: 'News',
    reportedAbsence: 'Reported Absence',
    onlineRequest: 'Online Request',
    attendedOnline: 'Attended Online',
    completed: 'Completed',
    startsAt: 'Starts at:',
    durationMinutesLabel: 'Duration:',
    reason: 'Reason:',
    reviewSubmission: 'Review Submission',
    viewHomework: 'View Homework',
    continueDraft: 'Continue Draft',
    doHomework: 'Do Homework',
    multipleAssignmentsNotice: 'assignments (select below)',
    cancelRequest: 'Cancel Request',
    attended: 'Attended',
    wasAbsent: 'Absent',
    requestAbsenceOrOnline: 'Request Absence / Online',
    reportAbsenceBtn: 'Report Absence',
    teacherAnnouncement: 'Teacher Announcement',
    sessionDetailsAndPrep: 'Session Details & Preparation',
    part: 'Part',
    timeAllocation: 'Time:',
    classActivity: 'Class Activity:',
    studentPrepRequired: 'Student Preparation:',
    noSpecialPrep: '(No special preparation required)',
    viewPastedText: 'View Pasted Lesson Text',
    downloadHandout: 'Download Material:',
    noDetailedPlanYet: 'No detailed plan for this session yet.',
    linkedAssignments: 'Assignments linked to this session',
    gradedBadge: 'Graded:',
    submittedBadge: 'Submitted',
    draftBadge: 'Draft',
    notSubmittedBadge: 'Not Submitted',
    doThisAssignment: 'Do This Assignment',
    attachmentsCount: 'Attachments',

    // Student Portal - Submission Modal
    submitHomework: 'Submit Homework',
    resubmitHomework: 'Resubmit',
    submittedReview: 'Review Submission',
    draftRestored: 'Auto-saved draft restored.',
    draftSaved: 'Draft saved automatically.',
    submissionModalTitle: 'Submit Assignment',
    assignmentInstructions: 'Assignment Instructions:',
    noDetailedInstructions: 'No detailed instructions provided.',
    teacherAttachments: 'Teacher\'s Attachments',
    assessmentResultTitle: 'Assessment & Feedback Results',
    submissionStatusTitle: 'Your Submission Status',
    teacherGradedDetailedNotice: 'Teacher has graded and provided detailed feedback',
    submittedAwaitingGradeNotice: 'Submitted, awaiting teacher grading',
    scoreLabel: 'Score:',
    awaitingGrade: 'Awaiting Grade',
    yourSubmittedContent: 'Your Submitted Content:',
    attachedFileLabel: 'Attachment:',
    downloadOrOpenFile: 'Download / Open ↗',
    deleteSubmissionNotice: 'You can delete this submission to resubmit if needed.',
    deleteSubmissionBtn: 'Delete Submission',
    deletingSubmission: 'Deleting...',
    storageNotice30Days: 'Storage Notice: Submissions are retained for 1 month (30 days) from submission date.',
    resubmitOrUpdate: 'Resubmit / Update Submission:',
    selectSubmissionFormat: 'Select Submission Format:',
    modeText: 'Text',
    modeDocx: 'Docx File',
    modeAudio: 'Audio File',
    modeRecord: 'Record Voice',
    modeImage: 'Photo / Camera',
    enterSubmissionTextLabel: 'Enter your submission text:',
    enterSubmissionTextPlaceholder: 'Type your answers here...',
    uploadDocxLabel: 'Upload Word document (.docx, .doc):',
    uploadingFile: 'Uploading file...',
    attachedLabel: 'Attached:',
    uploadAudioLabel: 'Upload audio file (.mp3, .wav, .m4a):',
    uploadingAudio: 'Uploading audio file...',
    submitWithPhotosLabel: 'Submit with Images / Photos:',
    uploadFromDevice: 'Upload photo (.jpg, .png)',
    takePhoto: 'Take Photo',
    captureThisPhoto: 'Capture Photo',
    stopCamera: 'Stop Camera',
    uploadingPhoto: 'Uploading photo...',
    saveDraftBtn: 'Save Draft (Not Submitted)',
    submittingHomework: 'Submitting...',
    confirmSubmitHomework: 'Confirm & Submit',
    lessonHandoutModalTitle: 'Lesson Handout Content',

    // Student Portal - Absence Modal
    registerOnlineTitle: 'Register for Online Class',
    confirmAbsenceTitle: 'Confirm Session Absence',
    selectParticipationMode: 'Select attendance option:',
    requestOnlineOption: 'Request Online Class',
    onlineOptionDesc: 'Attend via Meet/Zoom, maintain 100% attendance',
    recommendedBadge: 'Recommended',
    fullAbsenceOption: 'Full Session Absence',
    fullAbsenceDesc: 'Absent, deducts 1 session from monthly quota',
    absenceQuotaBadge: 'Quota: 2 sessions/month',
    timePolicyLabel: 'Time policy:',
    atLeast4HoursNotice: 'At least 4 hours before session start',
    monthlyQuotaLabel: 'Monthly absence quota:',
    usedQuotaNotice: 'Used',
    howToGetLinkTitle: 'How to receive class link:',
    howToGetLinkDesc: 'After you submit, your teacher will be notified and will post the Google Meet/Zoom link in the Session Announcement. Look for the pulsing "News" badge on your schedule to join!',
    mandatoryCommitmentsTitle: 'Mandatory Make-up Commitments',
    commitmentDoc: 'I commit to reviewing the required materials for this session',
    commitmentHomework: 'I commit to completing and submitting all assigned homework on time',
    commitmentImpact: 'I understand that being absent may impact my English learning progress',
    reasonLabel: 'Reason',
    reasonOnlinePlaceholder: 'Enter reason for online class...',
    reasonAbsencePlaceholder: 'Enter reason for absence...',
    confirmOnlineBtn: 'Confirm Online Request',
    confirmAbsenceBtn: 'Confirm Absence',

    // Student Portal - Mobile Nav
    mobileNavAnnouncements: 'Announcements',
    mobileNavSchedule: 'Schedule',
    mobileNavClasses: 'Classes',
    mobileNavMistakes: 'Mistakes',
    mobileNavSettings: 'Settings',

    // TimetableGrid
    timetableGridTitle: 'Weekly Timetable',
    prevWeek: 'Previous Week',
    currentWeek: 'Current Week',
    nextWeek: 'Next Week',
    assignmentStatusLegend: 'Assignment status:',
    notStarted: 'Not started',
    inProgressLegend: 'In progress',
    completedOrGraded: 'Completed / Graded',
    classLegend: 'Class:',
    sessionDrawerTitle: 'Session Details',
    homeworkThisSession: 'Homework for this session',
    dayMon: 'Monday',
    dayTue: 'Tuesday',
    dayWed: 'Wednesday',
    dayThu: 'Thursday',
    dayFri: 'Friday',
    daySat: 'Saturday',
    daySun: 'Sunday',
    dayShortMon: 'Mon',
    dayShortTue: 'Tue',
    dayShortWed: 'Wed',
    dayShortThu: 'Thu',
    dayShortFri: 'Fri',
    dayShortSat: 'Sat',
    dayShortSun: 'Sun',

    // Class Management (ClassList & ClassDashboard)
    classManagementTitle: 'Class Management',
    classListSubtitle: 'List of all your teaching classes',
    activityLibrary: 'Activity Library',
    addNewClass: '+ New Class',
    classCodeCol: 'Class Code',
    classNameCol: 'Class Name',
    startDateCol: 'Start Date',
    endDateCol: 'End Date',
    actionsCol: 'Actions',
    coTeacherBadge: 'Co-teacher',
    copyClass: 'Copy',
    leaveClass: 'Leave Class',
    noClassesYetClickNew: 'No classes yet. Click "+ New Class" to get started.',
    createClassModalTitle: 'Create New Class',
    updateClassModalTitle: 'Update Class',
    updateClass: 'Update Class',
    className: 'Class Name',
    startDate: 'Start Date',
    endDate: 'End Date',
    classNameLabel: 'Class Name',
    startDateLabel: 'Start Date',
    endDateLabel: 'End Date',
    termLabel: 'Term:',
    sixMonthsSemester: '+6 months (Semester)',
    threeMonths: '+3 months',
    oneYear: '+1 year',
    storagePolicyNotice: 'Storage Policy: Teacher data (classes, schedule, books, sessions, plans) is stored for 6 months or until deleted. Student submissions are retained for 1 month from submission date.',
    saveChanges: 'Save Changes',
    createClassBtn: 'Create Class',
    duplicateClassTitle: 'Duplicate Class',
    newClassNameLabel: 'New Class Name',
    startCopyingBtn: 'Start Copying',
    confirmDeleteClassTitle: 'Confirm Delete Class',
    confirmLeaveClassTitle: 'Confirm Leave Class',
    confirmDeleteClassDesc: 'Are you sure you want to delete this class?',
    confirmLeaveClassDesc: 'Are you sure you want to leave this co-taught class?',

    // Session Management (SessionList)
    selectAll: 'Select All',
    deselectAll: 'Deselect',
    selectedSessionsCount: 'Selected',
    batchDelete: 'Batch Delete',
    batchDeleting: 'Deleting...',
    addSessionBtn: '+ Add Session',
    allSessionsFilter: 'All Sessions',
    upcomingOnlyFilter: 'Upcoming Only',
    sectionsCount: 'sections',
    noSectionsYet: 'No sections',
    sessionEnded: 'Completed',
    onlineStudentsBox: 'students requested online',
    sendRoomLinkBtn: 'Send Room Link',
    urgentAnnouncementTitle: 'Urgent announcement for students:',
    editAnnouncementBtn: 'Edit announcement',
    hidePlanBtn: 'Hide Plan',
    viewPlanBtn: 'View Plan',
    addSectionBtn: '+ Add Section',
    attendanceBtn: 'Attendance',
    moreOptions: 'More options',
    copyNextWeek: 'Copy to next week (+7 days)',
    customCopySession: 'Custom Copy',
    copyPlanToAnother: 'Copy plan to another session',
    editSessionBtn: 'Edit Session',
    deleteSessionBtn: 'Delete Session',
    sectionLabel: 'Section',
    activityLabel: 'Activity:',
    prepLabel: 'Student Preparation:',
    bookLabel: 'Book:',
    pageLabel: 'Page',
    handoutLabel: 'Lesson Handout:',
    viewTextBtn: 'View Text',
    downloadFileBtn: 'Download File:',
    copySectionBtn: 'Copy Section',
    noSessionsYetTitle: 'No sessions created in this class yet.',
    noSessionsYetSubtitle: 'Click "+ Add Session" to start planning your curriculum.',
    createSessionModalTitle: 'Add New Session (+ Teaching Plan)',
    topicLabel: 'Session Topic',
    startTimeLabel: 'Start Time',
    durationLabel: 'Duration (mins)',
    detailedPlanOptional: 'Session Detailed Plan (Optional)',
    teachingContentLabel: 'Teaching Content',
    selectFromLibrary: 'Select from Library',
    handoutTypeNone: 'None',
    handoutTypeText: 'Paste Text',
    handoutTypeFile: 'Attach File',
    addNextSectionBtn: '+ Add Next Section',
    createSessionSubmitBtn: 'Create Session',
    editSessionModalTitle: 'Edit Session',
    copySessionModalTitle: 'Copy Session',
    includePlanCheckbox: 'Include detailed teaching plan',
    startSessionCopyBtn: 'Start Copying',
    updateSectionModalTitle: 'Update Section',
    addSectionModalTitle: 'Add Section to Session',
    saveSectionBtn: 'Save Section',
    copyPlanModalTitle: 'Copy Teaching Plan',
    targetSessionPicker: 'Select destination session to paste plan:',
    pastePlanBtn: 'Paste Plan to This Session',
    urgentAnnouncementModalTitle: 'Urgent Session Announcement',
    announcementNoticeStudent: 'Announcement content (Highlighted for students):',
    deleteAnnouncementBtn: 'Delete Announcement',
    saveAnnouncementBtn: 'Save Announcement',

    // Attendance Management (AttendanceManager)
    attendanceManagementTitle: 'Attendance Management',
    bySessionMode: 'By Session',
    matrixMode: 'Attendance Matrix',
    selectSessionLabel: 'Select Session:',
    allPresentBtn: 'Mark All Present',
    saveAttendanceBtn: 'Save Attendance',
    presentStat: 'Present',
    onlineStat: 'Online',
    lateStat: 'Late',
    excusedStat: 'Excused',
    unexcusedStat: 'Absent',
    unrecordedStat: 'Unrecorded',
    statusPresent: 'Present',
    statusOnline: 'Online',
    statusLate: 'Late',
    statusExcused: 'Excused',
    statusAbsent: 'Absent',
    statusUnrecorded: 'Unrecorded',
    exportAttendanceExcel: 'Export Excel',

    // Assignment Grade Matrix
    gradeMatrixTitle: 'Assignment Grade Matrix',
    exportGradeMatrixExcel: 'Export Grades (Excel/CSV)',
    reloadMatrixBtn: 'Reload Data',
    classSizeKpi: 'Class Size',
    studentsKpi: 'students',
    totalAssignmentsKpi: 'Total Assignments',
    assignmentsKpi: 'assignments',
    completionRateKpi: 'Completion Rate',
    classAvgScoreKpi: 'Class Average Score',
    noGradesYet: 'No grades yet',
    searchStudentPlaceholder: 'Search by student name, email...',
    filterAllStudents: 'All Students',
    filterIncompleteSubmissions: 'Incomplete Submissions',
    filterLowScores: 'Needs Attention: Score < 5.0',
    filterPerfectScores: 'Excellent & Complete',
    sortNameAsc: 'Sort: Name A → Z',
    sortScoreDesc: 'Average Score (High → Low)',
    sortScoreAsc: 'Average Score (Low → High)',
    sortCompletionDesc: 'Completion Rate (High → Low)',
    sttCol: '#',
    studentCol: 'Student',
    submittedCol: 'Submitted',
    avgScoreCol: 'Avg Score',
    quickGradeTitle: 'Grade & Feedback for Submission',
    quickScoreLabel: 'Score (out of 10):',
    quickFeedbackLabel: 'Teacher Feedback:',
    quickGradeSaveBtn: 'Save Grade Quickly',

    // Student List (StudentList & AllStudentsList)
    enrolledStudentsTitle: 'Enrolled Students',
    allStudentsTitle: 'All Students',
    addNewStudentBtn: '+ Add New Student',
    copyInfoBtn: 'Copy Info',
    copyToClassBtn: 'Copy to Class',
    removeFromClassBtn: 'Remove from Class',
    deleteStudentAccountBtn: 'Delete Account',
    noStudentsInClass: 'No students enrolled in this class yet. Click "+ Add New Student" to enroll.',
    addStudentModalTitle: 'Add New Student',
    fullNameLabel: 'Full Name',
    emailLabel: 'Email',
    selectClassOptional: 'Assign to class (Optional):',
    assignToClassModalTitle: 'Assign Student to Class',
    assignBtn: 'Assign to Class',

    // Account Settings (AccountSettingsModal)
    profileTab: 'Personal Info',
    enrolledClassesTab: 'Enrolled Classes',
    securityTab: 'Change Password',
    dangerZoneTab: 'Danger Zone',
    personalInfoTitle: 'Update Personal Info',
    fullNameRequiredMsg: 'Full name cannot be empty.',
    updateProfileBtn: 'Save Info',
    updatingProfile: 'Saving...',
    changePasswordTitle: 'Change Password',
    currentPasswordLabel: 'Current password',
    newPasswordLabel: 'New password (min 6 chars)',
    confirmPasswordLabel: 'Confirm new password',
    updatePasswordBtn: 'Update Password',
    updatingPassword: 'Updating...',
    enrolledClassesListTitle: 'Classes You Are Enrolled In',
    noEnrolledClasses: 'You have not enrolled in any classes.',
    leaveClassBtn: 'Leave Class',
    leavingClass: 'Leaving...',
    dangerZoneTitle: 'Permanently Delete Account',
    dangerZoneDesc: 'Once deleted, all your learning data, submissions, and history will be permanently erased and cannot be restored.',
    deleteAccountWarning: 'Please type "DELETE ACCOUNT" to confirm:',
    deleteAccountConfirmInputLabel: 'Type confirmation text',
    deleteAccountBtn: 'Confirm Permanent Deletion',
    deletingAccount: 'Deleting account...',

    // Student List & All Students List Extended
    studentListTitle: 'Student List',
    studentListSubtitle: 'Manage students enrolled in this class',
    studentsUnit: 'students',
    searchStudentPlaceholder: 'Search by name or email...',
    copyInfoFullBtn: 'Copy Info',
    copyToOtherClassBtn: 'To other class',
    removeStudentFromClassBtn: 'Remove from class',
    addStudentToClassModalTitle: 'Add Student to Class',
    studentFullNameLabel: 'Student Full Name',
    emailIdentityLabel: 'Email (Identity)',
    studentEmailExistNote: 'If the email already exists in the system, the student will automatically be enrolled in this class.',
    confirmAddBtn: 'Confirm Add',
    updateStudentModalTitle: 'Update Student Information',
    saveChangesBtn: 'Save Changes',
    copyStudentToOtherClassTitle: 'Copy Student to Another Class',
    enrollStudentPrefix: 'Enroll student',
    intoAnotherClass: 'into another class.',
    noOtherClasses: 'No other classes available in the system to copy to.',
    selectTargetClassLabel: 'Select target class',
    confirmCopyClassBtn: 'Confirm Copy',
    removeStudentConfirmTitle: 'Remove Student from Class',
    removeStudentConfirmDesc: 'Are you sure you want to unenroll student',
    fromThisClassDesc: 'from this class?',
    confirmDeleteStudentBtn: 'Confirm Delete',
    noStudentFoundMatch: 'No students matching search query.',
    emptyClassStudentPrompt: 'No students in this class yet. Click "Add Student".',
    allStudentsTitleFull: 'All Students List (All Classes)',
    allStudentsSubtitleDesc: 'Overview of all students in the system, enrolled classes, and enrollment management',
    totalStudentsKpi: 'Total Students',
    totalClassesKpi: 'Total Classes',
    totalEnrollmentsKpi: 'Total Enrollments',
    notInAnyClassKpi: 'Not Enrolled in Any Class',
    allClassesFilterOption: '-- All Classes --',
    studentsNotInAnyClassOption: 'Students not in any class',
    classColLabel: 'Class',
    enrolledClassesCol: 'Enrolled Classes',
    notInAnyClassBadge: 'Not enrolled in any class',
    unnamedStudent: 'Unnamed Student',
    loadingAllStudents: 'Loading school-wide student list...',
    noStudentsFoundTitle: 'No students found',
    noStudentsFoundSubtitle: 'Try changing search keywords or class filters.',
    noStudentsInSystemSubtitle: 'No students in the system yet.',
    createStudentModalDesc: 'Create a student account and assign directly to a class (optional)',
    emailGmailLabel: 'Account Gmail',
    assignToClassImmediately: 'Assign to class immediately:',
    notAssignedYetOption: '-- Not assigned yet (Add to system first) --',
    addingStudentProgress: 'Adding...',
    assignStudentModalTitle: 'Assign Student to Class',
    studentLabelPrefix: 'Student:',
    selectClassToAddLabel: 'Select class to add student to:',
    selectOneClassPrompt: '-- Select a class --',
    assigningToClass: 'Assigning...',
    addToClassBtn: 'Add to Class',

    // Account Settings Modal Extended
    accountSettingsTitle: 'Account Settings',
    personalInfoTab: 'Personal Info',
    myClassesTab: 'My Classes',
    changePasswordTab: 'Change Password',
    emailLoginLabel: 'Email Address (Login Identity):',
    emailFixedNote: 'Email is fixed to link submissions and classes.',
    fullNameDisplayLabel: 'Display Full Name:',
    fullNamePlaceholder: 'Enter your full name...',
    systemRoleLabel: 'System Role:',
    studentRoleBadge: 'Student (STUDENT)',
    teacherRoleBadge: 'Teacher (TEACHER)',
    saveProfileChangesBtn: 'Save Profile Changes',
    myClassesDesc: 'List of classes you have enrolled in. You can leave a class if you are no longer attending.',
    noEnrolledClassesMsg: 'You have not joined any classes yet.',
    classCodePrefix: 'Class Code:',
    teacherPrefix: 'Teacher:',
    leaveClassButton: 'Leave Class',
    leavingClassProgress: 'Leaving...',
    currentPasswordInputLabel: 'Current Password:',
    currentPasswordInputPlaceholder: 'Enter current password...',
    newPasswordInputLabel: 'New Password:',
    newPasswordInputPlaceholder: 'At least 6 characters...',
    confirmNewPasswordInputLabel: 'Confirm New Password:',
    confirmNewPasswordInputPlaceholder: 'Re-enter new password...',
    updatePasswordSubmitBtn: 'Update Password',
    updatingPasswordProgress: 'Updating Password...',
    dangerZoneDeleteTitle: 'Permanently Delete Account',
    dangerZoneDeleteDesc: 'This action will permanently delete your account and all associated data (submissions, classes, enrollments). This action cannot be undone.',
    dangerConfirmTextLabel: 'Type DELETE ACCOUNT to confirm:',
    dangerConfirmPlaceholder: 'DELETE ACCOUNT',
    dangerDeleteAccountBtn: 'I Understand the Consequences, Permanently Delete Account',
    deletingAccountProgress: 'Deleting...',
    logoutAccountBtn: 'Log Out Account',

    // SessionList & Teaching Plans Extended
    sessionsAndPlansTitle: 'Sessions & Teaching Plans',
    sessionsUnit: 'sessions',
    addNewSessionBtn: '+ Add New Session',
    sessionsSelected: 'Selected session(s)',
    copyToNextWeekBtn: 'Copy to next week (+7 days)',
    deleteSelectedSessionsBtn: 'Delete selected sessions',
    deselectBtn: 'Deselect',
    noSessionsInClass: 'No sessions in this class yet',
    createFirstSessionDesc: 'Click the button below to create the first session with detailed teaching plans for students.',
    addSessionAndPlanNow: '+ Add Session & Plan Now',
    upcomingSessionsTitle: 'Upcoming Sessions',
    pastSessionsTitle: 'Past Sessions',
    sectionsCount: 'sections',
    noSectionsYet: 'No sections yet',
    sessionCompleted: 'Completed',
    startTimeLabel: 'Start:',
    durationLabel: 'Duration:',
    expectedEndTimeLabel: 'Estimated end:',
    studentsRequestedOnline: 'students requested Online',
    sendRoomLinkBtn: 'Send room link',
    urgentAnnouncementLabel: 'Urgent announcement for students:',
    editAnnouncementBtn: 'Edit Notice',
    viewPlanBtn: 'View Plan',
    hidePlanBtn: 'Hide Plan',
    addSectionBtn: '+ Add Section',
    attendanceBtn: 'Attendance',
    announcementBtn: 'Notice',
    copyToNextWeek7d: 'Copy to next week (+7 days)',
    customCopySession: 'Custom Copy',
    editUrgentNotice: 'Edit urgent notice',
    addUrgentNotice: 'Add urgent notice',
    editSessionInfo: 'Edit session info',
    deleteThisSession: 'Delete this session',
    detailedPlanTitle: 'Detailed Teaching Plan',
    detailedPlanSubtitle: 'Students can see book content, preparations, and handouts in their timetable',
    copyPlanToAnotherSession: 'Copy plan to another session',
    addNewSectionPlanBtn: '+ Add New Section',
    noSectionsInPlanMsg: 'This session has no detailed sections yet.',
    inputFirstSectionBtn: '+ Add First Section',
    sectionPrefix: 'Section',
    timeAllocationLabel: 'Time allocation:',
    lessonContentLabel: 'Lesson content:',
    preparationLabel: 'Student preparation:',
    activityLabel: 'Class activity:',
    handoutLabel: 'Handout:',
    bookPageLabel: 'Book page:',
    downloadHandoutBtn: 'Download handout',
    viewHandoutTextBtn: 'View handout text',
    openBookPageBtn: 'Open book page',
    editSectionBtn: 'Edit',
    deleteSectionBtn: 'Delete',
    activityLibraryBtn: 'Activity Library',
    processingStatus: 'Processing...',
    deletingStatus: 'Deleting...',
    deselectGroup: 'Deselect this group',
    selectAllGroup: 'Select all in this group',
    noUpcomingSessionsInClass: 'No upcoming sessions.',
    copySessionModalTitle: 'Customize Session Copy',
    copySessionModalSubtitle: 'Duplicate this session and customize title or time.',
    newSessionTopicLabel: 'New session topic',
    copyAllPlansCheckbox: 'Copy all plans & sections to new session',
    confirmDuplicateBtn: 'Confirm Duplicate',
    deleteSessionModalTitle: 'Confirm Session Deletion',
    confirmDeleteSessionMsg: 'Are you sure you want to delete session',
    confirmDeleteSessionWarning: 'Teaching plans and attendance records for this session will also be removed.',
    permanentDeleteBtn: 'Permanently Delete',
    createSessionModalTitle: 'Add New Session',
    createSessionModalSubtitle: 'Schedule session and optionally prepare teaching plan',
    step1SessionInfo: '1. Session Information',
    step2TeachingPlan: '2. Input detailed teaching plan for this session',
    sessionTopicLabel: 'Session Topic / Title',
    enterTopicPlaceholder: 'Enter session topic...',
    minutesUnit: 'Minutes',
    createSessionAndPlanBtn: 'Create Session & Plan',
    creatingStatus: 'Creating...',
    editSessionModalTitle: 'Edit Session Information',
    urgentAnnouncementModalTitle: 'Urgent Session Announcement',
    urgentAnnouncementInputLabel: 'Announcement message for students:',
    enterAnnouncementPlaceholder: 'Enter announcement...',
    deleteAnnouncementBtn: 'Delete Announcement',
    saveAnnouncementBtn: 'Save Announcement',
    savingStatus: 'Saving...',
    copyPlanModalTitle: 'Copy Plan to Another Session',
    copyPlanModalSubtitle: 'Select a target session in this class to paste all sections from the current plan.',
    targetSessionLabel: 'Target Session:',
    selectSessionPrompt: '-- Select session --',
    pastePlanBtn: 'Paste Plan',
    viewPastedTextTitle: 'Pasted Text Content',
    sectionModalAddTitle: 'Add Section to Session',
    sectionModalEditTitle: 'Edit Section',
    saveSectionBtn: 'Save Section',
    textbookAndPageLabel: 'Textbook & Page Number (Optional)',
    openBookPickPageBtn: 'Open Book & Pick Page',
    selectTextbookPrompt: '-- Select class textbook --',
    pagePlaceholder: 'Page (e.g. 45)',
    sectionContentLabel: 'Section Content (Topic / Lesson Knowledge)',
    enterSectionContentPlaceholder: 'Enter section content...',
    timeAllocationPrompt: 'Time (e.g. 15 mins)',
    classActivityLabel: 'Classroom Activity',
    pickFromActivityBankBtn: 'Pick from Bank',
    unselectBtn: 'Deselect',
    studentHomePrepLabel: 'Student Preparation at Home:',
    homePrepPlaceholder: 'Students preview page 24, do warmup exercises...',
    attachedHandoutLabel: 'Attached Handout',
    noHandoutOption: 'None',
    pasteTextOption: 'Paste lesson text',
    uploadFileOption: 'Upload attachment (.docx, .pdf, .png...)',
    pasteTextareaPlaceholder: 'Paste full text or reading material here...',
    uploadingHandoutStatus: 'Uploading file...',
    attachedPrefix: 'Attached:',

    // Assignment Manager Extended
    assignmentManagementTitle: 'Assignment Management',
    assignmentsUnit: 'assignments',
    allSessionsOption: 'All Sessions',
    newAssignmentBtn: 'Create Assignment',
    scheduledPublishPrefix: 'Scheduled to publish:',
    sessionTimePrefix: 'Session time:',
    publishNowBtn: 'Publish Now',
    duplicateBtn: 'Duplicate',
    viewSubmissionsBtn: 'View submissions',
    hideSubmissionsBtn: 'Hide submissions',
    studentSubmissionsHeading: 'Student Submissions List',
    allStatusFilter: 'All statuses',
    statusSubmitted: 'Submitted',
    statusGraded: 'Graded',
    statusUnsubmitted: 'Not submitted',
    submissionTimeCol: 'Submission Time',
    unsubmittedStatus: 'Not submitted',
    lateSubmission: 'Late submission',
    onTimeSubmission: 'On time',
    gradeSubmissionBtn: 'Grade',
    editGradeBtn: 'Edit Grade',
    speedGraderAction: 'SpeedGrader',
    createAssignmentModalTitle: 'Create New Assignment',
    editAssignmentModalTitle: 'Edit Assignment',
    associatedSessionLabel: 'Associated Session',
    assignmentTitleLabel: 'Assignment Title',
    assignmentDescLabel: 'Instructions / Description',
    dueDateLabel: 'Due Date',
    scheduledPublishLabel: 'Schedule Publication (Optional)',
    allowedSubmissionTypesLabel: 'Allowed Submission Types',
    allowTextType: 'Text entry',
    allowDocxType: 'Word / PDF file upload',
    allowAudioType: 'Audio file upload',
    allowRecordingType: 'In-app voice recording',
    allowImageType: 'Image file upload',
    attachmentsLabel: 'Teacher Attachments',
    uploadAttachmentBtn: '+ Add Attachment',
    viewSubmissionsList: 'View Submissions',
    viewingSubmissions: 'Viewing Submissions',
    remindUnsubmitted: 'Remind unsubmitted',
    noReminderForThis: 'Skip reminders',
    remindersDisabled: 'Reminders disabled',
    downloadZip: 'Download ZIP',
    totalStudentsLabel: 'Total students:',
    submittedCountLabel: 'Submitted:',
    unsubmittedCountLabel: 'Unsubmitted:',
    loadingSubmissionsList: 'Loading student submissions...',
    studentCol: 'Student',
    statusCol: 'Status',
    submissionFormatCol: 'Submission Format',
    scoreCol: 'Score',
    actionCol: 'Actions',
    ungraded: 'Ungraded',
    viewAndGradeBtn: 'View & Grade',
    noSubmissionText: 'No submission',
    noAssignmentsYet: 'No assignments yet',
    createFirstAssignmentPrompt: 'Click "Create Assignment" to assign homework for students in this class',
    createFirstAssignmentBtn: 'Create First Assignment',
    gradeAndFeedbackModalTitle: 'Grade & Feedback Submission',
    studentLabel: 'Student:',
    prevStudent: '‹ Prev',
    nextStudent: 'Next ›',
    submissionContentTitle: 'Student Submission Content',
    submittedAtLabel: 'Submitted at:',
    emptySubmissionNotice: '(Empty submission)',
    downloadDocxBtn: 'Download & View file',
    openOriginalImage: 'Open original image ↗',
    audioNotFound: 'Audio file URL not found.',
    imageNotFound: 'Image URL not found.',
    scoreInputLabel: 'Score',
    scoreInputPlaceholder: 'e.g. 8.5/10, Band 7.0, A+...',
    teacherFeedbackLabel: 'Teacher Feedback & Recommendations',
    clickChipToInsert: 'Click chip to insert',
    feedbackPlaceholder: 'Strengths, areas for improvement, pronunciation/grammar notes...',
    saveGradeAndFeedbackBtn: 'Save Grade & Send Feedback',
    savingGradeStatus: 'Saving...',
    publishTimingLabel: 'Publish timing for students',
    publishImmediately: 'Publish Immediately',
    schedulePublishBtn: 'Schedule Release',
    scheduledPushTime: 'Automatic release time (Push)',
    max5Attachments: 'Teacher attachments (Max 5 files)',
    selectedCount: 'Selected:',
    uploadingAttachmentStatus: 'Uploading attachment...',
    saveUpdateBtn: 'Save Changes',
    assignHomeworkBtn: 'Assign Homework',
    unlimitedDue: 'No deadline',
    loadingAssignmentsList: 'Loading assignments...',
    dueDatePrefix: 'Due date:',
    allowedSubmissionTypes: 'Allowed submission formats:',
    attachedTaskFiles: 'Attached assignment files',

    // Login & Register Extended
    trainingSystemSubtitle: 'Training & Classroom Management System',
    loginTab: 'Log In',
    registerTab: 'Register New Account',
    emailLoginInput: 'Login Email',
    passwordInput: 'Password',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    loginSubmitBtn: 'Log In',
    authenticatingProgress: 'Authenticating...',
    registerFullNameLabel: 'Full Name',
    registerEmailLabel: 'Gmail Address',
    accountRoleLabel: 'Account Role',
    teacherRoleOption: 'Teacher',
    studentRoleOption: 'Student',
    passwordMinChars: 'Password (at least 6 characters)',
    confirmPasswordInput: 'Confirm Password',
    passwordMatch: 'Passwords match',
    passwordMismatch: 'Passwords do not match',
    registerSubmitBtn: 'Create Account & Get Started',
    creatingAccountProgress: 'Creating account...',
    orContinueWith: 'Or continue with'
  }
};

export function ThemeLanguageProvider({ children }) {
  const [theme, setTheme] = useState(() => {
    try {
      const saved = localStorage.getItem('app_theme');
      return saved ? saved : 'light';
    } catch {
      return 'light';
    }
  });

  const [lang, setLang] = useState(() => {
    try {
      const saved = localStorage.getItem('app_lang');
      return saved ? saved : 'vi';
    } catch {
      return 'vi';
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem('app_theme', theme);
    } catch {}
    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
      document.body.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
      document.body.classList.remove('dark');
    }
  }, [theme]);

  useEffect(() => {
    try {
      localStorage.setItem('app_lang', lang);
    } catch {}
  }, [lang]);

  const toggleTheme = () => {
    setTheme(prev => (prev === 'dark' ? 'light' : 'dark'));
  };

  const toggleLanguage = () => {
    setLang(prev => (prev === 'vi' ? 'en' : 'vi'));
  };

  const t = useMemo(() => {
    return (key, fallback = '') => {
      const currentDict = dictionary[lang] || dictionary.vi;
      return currentDict[key] || fallback || key;
    };
  }, [lang]);

  const value = {
    theme,
    lang,
    toggleTheme,
    toggleLanguage,
    setTheme,
    setLang,
    t
  };

  return (
    <ThemeLanguageContext.Provider value={value}>
      {children}
    </ThemeLanguageContext.Provider>
  );
}

export function useThemeLanguage() {
  const context = useContext(ThemeLanguageContext);
  if (!context) {
    throw new Error('useThemeLanguage must be used within ThemeLanguageProvider');
  }
  return context;
}

export function ThemeLanguageToggle() {
  const { theme, lang, setTheme, setLang, t } = useThemeLanguage();

  return (
    <div className="flex items-center gap-1.5 select-none text-[11px] font-sans">
      {/* Bộ chọn ngôn ngữ VI / EN */}
      <div className="inline-flex rounded-sm p-0.5 bg-slate-950/90 border border-slate-700/80 shadow-2xs">
        <button
          type="button"
          onClick={() => setLang('vi')}
          title="Tiếng Việt"
          className={`px-1.5 py-0.5 rounded-xs transition cursor-pointer font-bold ${
            lang === 'vi'
              ? 'bg-blue-600 text-white shadow-xs'
              : 'text-slate-400 hover:text-slate-200'
          }`}>
          VI
        </button>
        <button
          type="button"
          onClick={() => setLang('en')}
          title="English"
          className={`px-1.5 py-0.5 rounded-xs transition cursor-pointer font-bold ${
            lang === 'en'
              ? 'bg-blue-600 text-white shadow-xs'
              : 'text-slate-400 hover:text-slate-200'
          }`}>
          EN
        </button>
      </div>

      {/* Bộ chọn giao diện Sáng / Tối */}
      <div className="inline-flex rounded-sm p-0.5 bg-slate-950/90 border border-slate-700/80 shadow-2xs">
        <button
          type="button"
          onClick={() => setTheme('light')}
          title={lang === 'vi' ? 'Giao diện Sáng' : 'Light Mode'}
          className={`px-1.5 py-0.5 rounded-xs transition cursor-pointer font-semibold ${
            theme === 'light'
              ? 'bg-slate-200 text-slate-900 shadow-xs'
              : 'text-slate-400 hover:text-slate-200'
          }`}>
          {t('lightMode')}
        </button>
        <button
          type="button"
          onClick={() => setTheme('dark')}
          title={lang === 'vi' ? 'Giao diện Tối' : 'Dark Mode'}
          className={`px-1.5 py-0.5 rounded-xs transition cursor-pointer font-semibold ${
            theme === 'dark'
              ? 'bg-blue-600 text-white shadow-xs'
              : 'text-slate-400 hover:text-slate-200'
          }`}>
          {t('darkMode')}
        </button>
      </div>
    </div>
  );
}
